AllCops:
  TargetRubyVersion: 3.0

Documentation:
  Enabled: false

Line/MissingSuper:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
